#!/usr/bin/env python3
"""Generates docs/mitre-coverage.json (an ATT&CK Navigator layer) and
docs/mitre-coverage.md (a human-readable table) from the <mitre><id>
tags in rules/*.xml.

Both files are generated artifacts - do not hand-edit them, re-run this
script after changing a rule's MITRE tags:

    python3 scripts/generate_mitre_navigator_layer.py

Import the .json at https://mitre-attack.github.io/attack-navigator/ to
see coverage plotted on the actual matrix.
"""
import json
import xml.etree.ElementTree as ET
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).parent.parent
RULES_DIR = ROOT / "rules"
DOCS_DIR = ROOT / "docs"


def collect_coverage() -> dict[str, list[str]]:
    coverage: dict[str, list[str]] = defaultdict(list)
    for path in sorted(RULES_DIR.glob("*.xml")):
        tree = ET.parse(path)
        for rule in tree.getroot().findall("rule"):
            rid = rule.get("id")
            desc_el = rule.find("description")
            desc = desc_el.text.strip() if desc_el is not None and desc_el.text else ""
            for mitre in rule.findall("mitre"):
                for tid in mitre.findall("id"):
                    if tid.text:
                        coverage[tid.text.strip()].append(f"{rid}: {desc}")
    return coverage


def write_navigator_layer(coverage: dict[str, list[str]]) -> None:
    layer = {
        "name": "Wazuh Detection Lab Coverage",
        "versions": {"attack": "17", "navigator": "5.1.0", "layer": "4.5"},
        "domain": "enterprise-attack",
        "description": "Auto-generated from rules/*.xml <mitre> tags - see scripts/generate_mitre_navigator_layer.py",
        "techniques": [
            {"techniqueID": tid, "score": 1, "comment": "; ".join(rules)}
            for tid, rules in sorted(coverage.items())
        ],
        "gradient": {"colors": ["#ffffff", "#66b1ff"], "minValue": 0, "maxValue": 1},
        "legendItems": [{"label": "Covered by a custom rule in this repo", "color": "#66b1ff"}],
    }
    out = DOCS_DIR / "mitre-coverage.json"
    out.write_text(json.dumps(layer, indent=2) + "\n")
    print(f"wrote {out.relative_to(ROOT)}")


def write_markdown_table(coverage: dict[str, list[str]]) -> None:
    lines = [
        "# MITRE ATT&CK Coverage",
        "",
        "Auto-generated by `scripts/generate_mitre_navigator_layer.py` from the "
        "`<mitre>` tags in `rules/*.xml`. Do not hand-edit - regenerate after "
        "changing rules.",
        "",
        "Import `mitre-coverage.json` into the "
        "[ATT&CK Navigator](https://mitre-attack.github.io/attack-navigator/) "
        "to visualize this on the matrix.",
        "",
        "| Technique | Covering rule(s) |",
        "|---|---|",
    ]
    for tid, rules in sorted(coverage.items()):
        lines.append(f"| {tid} | {'<br>'.join(rules)} |")
    out = DOCS_DIR / "mitre-coverage.md"
    out.write_text("\n".join(lines) + "\n")
    print(f"wrote {out.relative_to(ROOT)}")


def main() -> None:
    coverage = collect_coverage()
    write_navigator_layer(coverage)
    write_markdown_table(coverage)
    print(f"{len(coverage)} technique(s) covered across "
          f"{len(list(RULES_DIR.glob('*.xml')))} rule file(s).")


if __name__ == "__main__":
    main()
